import React from 'react';
import { ArrowRight, BarChart3, Boxes, FileCheck2, Landmark, ReceiptIndianRupee, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/Button';

const features = [
  [ReceiptIndianRupee, 'Accounts & vouchers', 'Maintain cash, bank, contra and journal vouchers with complete control.'],
  [Boxes, 'Inventory management', 'Track raw material, finished goods, GRN and purchase activity in one place.'],
  [BarChart3, 'Business reports', 'Make better decisions with sales, purchase, stock and ledger statements.']
];
export const Home: React.FC = () => <div className="overflow-hidden pb-20">
  <section className="relative pt-28 md:pt-36"><div className="absolute inset-x-0 top-0 -z-10 h-[520px] bg-[radial-gradient(ellipse_at_top_right,_#dcebf8_0%,_#f8fbfe_48%,_transparent_75%)]" /><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 lg:grid-cols-2"><div className="animate-rise"><span className="inline-flex items-center gap-2 rounded-full border border-[#d7e5f2] bg-white/80 px-3 py-1.5 text-xs font-bold text-[#37618c]"><ShieldCheck className="h-3.5 w-3.5" /> Built for growing businesses</span><h1 className="mt-6 max-w-xl text-4xl font-bold leading-[1.12] tracking-tight text-[#132f50] sm:text-5xl">One dependable system for your <span className="text-[#376fa9]">entire business.</span></h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-[#688099]">First Computer ERP brings accounting, inventory, sales, purchase and reporting into one organised workspace.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register"><Button className="gap-2 rounded-xl px-5 py-3">Register your company <ArrowRight className="h-4 w-4" /></Button></Link><Link to="/login"><Button variant="outline" className="rounded-xl px-5 py-3">Log in</Button></Link></div><p className="mt-6 text-xs font-medium text-[#8092a5]">Ahmedabad · 9426064310 · sanjay_zindal@rediffmail.com</p></div><div className="animate-rise relative" style={{ animationDelay: '120ms' }}><div className="rounded-[26px] border border-[#dce7f1] bg-white p-3 shadow-2xl shadow-[#244e78]/10"><div className="rounded-[18px] bg-[#f4f8fb] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#183c66] text-white"><Landmark className="h-4 w-4" /></span><b className="text-sm text-[#193758]">First Computer ERP</b></div><span className="h-2 w-16 rounded bg-[#d8e4ef]" /></div><div className="mt-6 grid grid-cols-3 gap-3">{['Sales Today','Purchase','Receivable'].map((x,i)=><div key={x} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-[9px] font-bold text-[#91a1b2]">{x}</p><p className="mt-2 text-sm font-bold text-[#244766]">{i === 0 ? '₹ 1.42L' : i === 1 ? '₹ 86.4K' : '₹ 48.2K'}</p></div>)}</div><div className="mt-4 rounded-xl bg-white p-4"><div className="mb-5 flex justify-between"><span className="text-xs font-bold text-[#3c5976]">Weekly sales</span><span className="text-[10px] text-[#82a06e]">+12.5%</span></div><div className="flex h-28 items-end gap-2">{[35,50,43,67,56,88,72].map((h,i)=><span key={i} style={{height:`${h}%`}} className={`flex-1 rounded-t-md ${i===5?'bg-[#2e6196]':'bg-[#cbddec]'}`} />)}</div></div></div></div></div></div></section>
  <section id="features" className="mx-auto mt-28 max-w-7xl px-6"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#6385a8]">ERP modules</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#183756]">Daily operations, beautifully organised.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(([Icon,title,text],i)=>{const FeatureIcon=Icon as typeof FileCheck2; return <article key={title as string} className="dashboard-card animate-rise rounded-2xl border border-[#e3ebf2] bg-white p-6 shadow-sm" style={{animationDelay:`${i*80}ms`}}><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#eaf2f9] text-[#366b9f]"><FeatureIcon className="h-5 w-5" /></span><h3 className="mt-5 font-bold text-[#1c3a59]">{title as string}</h3><p className="mt-2 text-sm leading-relaxed text-[#71859b]">{text as string}</p></article>})}</div></section>
</div>;
