import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as zod from 'zod';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { showToast } from '@/hooks/useToasts';
import { authApi } from '@/services/api';
const schema = zod.object({ email: zod.string().email('Please enter a valid email address') });
type Inputs = zod.infer<typeof schema>;
export const ForgotPassword: React.FC = () => { const { register, handleSubmit, formState: { errors } } = useForm<Inputs>({ resolver: zodResolver(schema) }); const [loading, setLoading] = React.useState(false); const onSubmit = async ({ email }: Inputs) => { setLoading(true); try { const result = await authApi.forgotPassword(email); showToast(result.success ? 'success' : 'error', result.message); } catch (error: any) { showToast('error', 'Unable to send reset link', error?.response?.data?.message || 'Please try again.'); } finally { setLoading(false); } }; return <div className="space-y-6 text-left"><div><h1 className="text-2xl font-bold text-text-primary">Reset password</h1><p className="mt-2 text-sm text-text-secondary">Enter the email registered with your company account.</p></div><form onSubmit={handleSubmit(onSubmit)} className="space-y-4"><div className="space-y-1.5"><label className="text-xs font-semibold text-text-secondary">Email Address</label><input type="email" {...register('email')} className="w-full rounded-xl border border-border px-4 py-2.5 text-sm outline-none focus:ring-2 focus:ring-primary/20" />{errors.email && <p className="text-xs text-red-500">{errors.email.message}</p>}</div><Button type="submit" isLoading={loading} className="w-full justify-center py-3">Send Instructions</Button></form><p className="text-center text-sm text-text-secondary">Remember credentials? <Link to="/login" className="font-semibold text-primary">Log In</Link></p></div>; };
